### ISSUE TITLE
fix meta for picture for facebook like option

### ISSUE THREAD

**Issue by danbjoseph** [osmlab/basket#16]
The "Like" option seems to be inconsistent and broken in the setting of a preview image. Should add the appropriate meta tags for this to either display nothing or the correct something?

**Comment by wuhland** [comment]
Yea see what you're saying, the facebook share preview image displays page not found but link works fine when clicked through. Looked at it for a bit - still not quite sure why that is happening.

**Comment by vknoppkewetzel** [comment]
This isn't fixing but this is helpful in seeing what shows up.... https://developers.facebook.com/tools/debug/

What seems to be happening is facebook is automatically grabbing the last image loaded on the site and using that as the preview thumbnail for the link.

Gonna see how we can change how facebook is grabbing images for that

**Comment by danbjoseph** [comment]
i fixed the og:url value and now the text for the share is displaying
should just be a matter of setting the og:img meta now

**Comment by danbjoseph** [comment]
- image works for posts if the YAML front matter includes a `facebook:` property nested under `'image:` and it should work with either a url or the file name of an image in the `images/posts/` folder
- [x] still needs better error checking for if there is no image (create a default image to use?)
- [ ] still need to have`_includes/open-graph.html` handle when someone shares a page that is not a post (i.e. if someone copies the URL of the map or about page and shares it manually on Facebook)
- [x] still need to update the YAML front matter in the other existing posts

![screen shot 2015-09-24 at 4 24 04 pm](https://cloud.githubusercontent.com/assets/4806884/10085733/c5ae0ed8-62d8-11e5-9c27-0360a67dbb38.png)

**Comment by d3netxer** [comment]
added an if statement to `_includes/open-graph.html` file that will default to using the author's avatar if there is no Facebook image property, sort of takes care of having to update the YAML front matter for the other posts.
